public class AccountTriggerHandler {

public static void deleteAccount(List<Account> accList)
{
    // List<Id> accIds = new List<Id>();

    // for(Account acc:accList)
    // {
    //     accIds.add(acc.Id);
    // }

    // List<Contact> contactList = [SELECT Id,Name FROM Contact WHERE AccountId IN: accIds];
    // Map<Id,Contact> contactMap = new Map<Id,Contact>();

    // for(Contact con : contactList)
    // {
    //     contactMap.put(con.Id,con);
    // }

    // for(Account acc:accList)
    // {
    //     if(contactMap.get(acc.Id).size()==0)
    //     {
    //         acc.addError('Account can\'t be deleted as it has associated contacts');
    //     }
    // }



}

}